owner: rybesh
repo: status

sites:
  - name: UNC-CH AAUP
    url: https://unc-ch-aaup.org
  - name: Deals
    url: https://deals.fly.dev
  - name: Feedme
    url: https://feedme.fly.dev
  - name: NC Gazetteer
    url: https://ncgazetteer.org

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/rybesh/status/master/assets/upptime-icon.svg
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
