owner: rybesh
repo: status

sites:
  - name: Aeshin
    url: https://aeshin.org
  - name: Linked Events
    url: https://linkedevents.org
  - name: UNC-CH AAUP
    url: https://unc-ch-aaup.org
  - name: Deals
    url: https://deals.fly.dev
  - name: Feedme
    url: https://feedme.fly.dev
  - name: NC Gazetteer
    url: https://ncgazetteer.org
  - name: Fedwiki
    url: https://fedwiki.fly.dev
    expectedStatusCodes:
      - 401

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
