owner: rybesh
repo: status

sites:
  - name: Aeshin
    url: https://aeshin.org
  - name: PeriodO data
    url: https://data.perio.do
  - name: PeriodO TTL
    url: https://n2t.net/ark:/99152/p0dataset.ttl

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
